GET http://localhost:9999/clientes/1/extrato HTTP/1.1
content-type: application/json
###
POST http://localhost:9999/clientes/1/transacoes HTTP/1.1
content-type: application/json

{
    "valor": 5000,
    "tipo" : "d",
    "descricao" : "descricao"
}